# Datasource properties of first datasource:
graal1:
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/graal1
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate.hbm2ddl.auto: update

# Datasource properties of second datasource:
graal2:
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/graal2
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate.hbm2ddl.auto: update
